### ISSUE TITLE
Does not work with async/await  - reopen of #309

### ISSUE THREAD

**Issue by BobrImperator** [san650/ember-cli-page-object#354] opened 2017-12-19 14:40 UTC
Reopening #309 

My package.json
```
"devDependencies": {
    "broccoli-asset-rev": "^2.4.5",
    "ember-ajax": "^3.0.0",
    "ember-can": "^0.8.5",
    "ember-cli": "~2.16.2",
    "ember-cli-app-version": "^3.0.0",
    "ember-cli-babel": "^6.6.0",
    "ember-cli-dependency-checker": "^2.0.0",
    "ember-cli-eslint": "^4.0.0",
    "ember-cli-htmlbars": "^2.0.1",
    "ember-cli-htmlbars-inline-precompile": "^1.0.0",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-mirage": "^0.4.0",
    "ember-cli-page-object": "^1.13.0-alpha.1",
    "ember-cli-qunit": "^4.0.0",
    "ember-cli-shims": "^1.1.0",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-template-lint": "^0.7.5",
    "ember-cli-uglify": "^2.0.0",
    "ember-data": "~2.16.2",
    "ember-export-application-global": "^2.0.0",
    "ember-load-initializers": "^1.0.0",
    "ember-local-storage": "^1.4.0",
    "ember-native-dom-helpers": "^0.5.10",
    "ember-parachute": "^0.3.6",
    "ember-resolver": "^4.0.0",
    "ember-source": "~2.16.0",
    "ember-test-selectors": "^0.3.8",
    "emberfire": "^2.0.8",
    "eslint-plugin-ember": "^5.0.0",
    "loader.js": "^4.2.3",
    "tachyons": "^4.9.0"
  },
  "engines": {
    "node": "9.2.0"
  },
  "dependencies": {
    "pikaday": "^1.6.1"
  }
}
```
and I am using the same workaround as in mentioned issue.

**Comment by ro0gr** [comment] 2017-12-19 21:51
@BobrImperator do you have your failure in acceptance or integration test? I ask this cause I think we have an issue here https://github.com/san650/ember-cli-page-object/blob/57183487aa9a8446861f4fbc52c03dbc02eeb1e6/addon/-private/execution_context/acceptance.js#L24
I think we should use `wait` from the `ember-test-helpers` here..

Also might be helpful to know if you use `nativeEvents` mode?

**Comment by BobrImperator** [comment] 2017-12-19 23:24
It happens on integration test, and I'm not using  nativeEvents mode, at least I think I'm not, I wasn't doing any customizations.

**Comment by ro0gr** [comment] 2017-12-26 22:02
@BobrImperator I think the fix should be trivial. However it would be better to have a minimal reproduction. Can you please provide a demo app?

**Comment by BobrImperator** [comment] 2017-12-28 15:33
Sorry for late response, here is dummy app.
I've created two commits, one with error setup, and second with error repair.
But literally all that is sufficient to get error ``window.wait is not a function`` is to get rid of beforeEach hook inside moduleForComponent

**Comment by san650** [comment] 2017-12-28 20:34
@BobrImperator the link is missing, I guess the dummy app is https://github.com/BobrImperator/page-object-dummy

**Comment by ro0gr** [comment] 2017-12-28 21:54
@BobrImperator I've checked your demo app and can't find any usages of `async`/`await`. I'm closing the issue. Feel free to re-open if I miss something.

----

Seems like the issue in your demo test is caused by invalid page object usage.
[Here](https://github.com/BobrImperator/page-object-dummy/commit/b68af84991cc9c9e03cdc9d60445b6b00746a3ba#diff-28c3095c102f844034c2475c07dfae58R20) you try to access `value` of [`fillable()`](https://github.com/BobrImperator/page-object-dummy/blob/master/tests/pages/item.js#L5) execution result which is not supported.

In order to fix the test I'd advice you to add a separate page object property which is responsible for reading input value:
```js
// pages/page.js
import { 
  fillable,
  visitable,
  value,
  create
} from 'ember-cli-page-object';

export default create({
  visit: visitable('/'),
  name: {
    scope: 'input',
    fill: fillable(),
    value: value()
  }
});
```

That would allow to make work your test:
```js
import { moduleForComponent, test } from 'ember-qunit';
import hbs from 'htmlbars-inline-precompile';
import page from 'page-object-dummy/tests/pages/item';

moduleForComponent('items-list', 'Integration | Component | items-list', {
  integration: true,
  beforeEach() {
    page.setContext(this);
  },
  afterEach() {
    page.removeContext();
  }
});

test('it fills input', function(assert) {
  this.render(hbs`{{item-list}}`);

  page.name.fill('Hello');

  assert.equal(page.name.value, 'Hello', 'it displays');
});
```

**Closed by ro0gr** 2017-12-28 21:54 UTC
Labels: bug
