### ISSUE TITLE
Integration test example misleading

### ISSUE THREAD

**Issue by simonihmig** [san650/ember-cli-page-object#270] opened 2016-12-08 00:23 UTC
I find the example of using ember-cli-page-object with integration tests a bit misleading as it is using a page object rather than a page object component. In the given login page example the page object and the component might match, as the page seems to consist only of that login form. But after using this addon a lot for quite a while, I never had this case. Usually the page contains so much more, with nested components/collections, that it does not fit the structure of a component to be tested in isolation. 

So usually when creating a new component, I also create a new matching page object component, that could be added to page object for acceptance tests, but for the component integration test they look something like this one:

```js
import { expect } from 'chai';
import { describeComponent, it } from 'ember-mocha';
import {
  beforeEach,
  afterEach
} from 'mocha';
import hbs from 'htmlbars-inline-precompile';
import navigationToggle from 'frontend/tests/pages/components/navigation-toggle';
import {
  create
} from 'ember-cli-page-object';

// Create a page object containing only our page object component
const page = create({
  navigationToggle
});
const component = page.navigationToggle;

describeComponent('navigation-toggle', 'Integration | Component | navigation toggle',
  {
    integration: true
  },
  function() {
    beforeEach(function() {
      page.setContext(this);
    });

    afterEach(function() {
      page.removeContext();
    });

    it('shows icon', function() {
      this.render(hbs`{{navigation-toggle icon="menu"}}`);
      expect(component.hasMenuIcon).to.be.true;
    });
  }
);
```

It seems you cannot use the page object component directly without it being part of a page object, so that's why I have this page setup before the tests.

Is this how it should be done? If so, would you consider changing the docs accordingly? Can also create a PR if you want...

**Comment by san650** [comment] 2016-12-14 18:49
Hi @simonihmig, sorry for the late response on this issue.

I see what you're saying and I think the problem goes beyond the example and has to do with the fact that we use the name "page object component". That name is misleading because it makes you expect that this "page object component" will behave like a page object when in fact it's just a plain old JavaScript object without any special behavior.

When you plug one of these "page object components" into a page object, they gain the special behavior we expect to see in a page object.

So to sum up, in ember-cli-page-object, a "page object component" is just a plain old JavaScript object and if we want to create a page object from it, we need to call the `create` function on it.

Let me share with you an example of how I'm using it:

`tests/pages/components/login-form.js`

```js
import {
  clickable,
  create,
  fillable,
  text,
  visitable
} from 'ember-cli-page-object';

const definition = {
  username: fillable('#username'),
  password: fillable('#password'),
  submit: clickable('button'),
  error: text('.errors')
};

// Just export the definition to use in other page objects
export default definition;

// Export the generated page object to use in component integration tests
export const component = create(definition);
```

and the component integration tests would look like:

```js
import { expect } from 'chai';
import { describeComponent, it } from 'ember-mocha';
import { beforeEach, afterEach } from 'mocha';
import hbs from 'htmlbars-inline-precompile';
import { component } from 'frontend/tests/pages/components/login-form';

describeComponent('navigation-toggle', 'Integration | Component | navigation toggle',
  {
    integration: true
  },
  function() {
    beforeEach(function() {
      component.setContext(this);
    });

    afterEach(function() {
      component.removeContext();
    });

    it('shows icon', function() {
      this.render(hbs`{{login-form}}`);
      expect(component.error).to.be(...);
    });
  }
);
```

This behavior is not expected and confusing and we should fix it. I'm not sure how yet but I have an idea, if we could compose page objects together, we could export the page object directly without the need to export the definition.

@simonihmig Does this makes sense? Does this answer your questions?

In the meantime, Can you think a way to clarify this on the documentation? I would love to have some help trying to clarify how all this works.

PS: Just to give more context on the issue, at first, ember-cli-page-object didn't have support for component integration tests, so the usage of the "page object component" was pretty clear, it was a way to share code between several page objects (and nothing more), after we added support for component integration tests, we all started to use "page object components" for component integration tests but we didn't fix the documentation and the blueprints accordingly (totally my fault).

**Comment by simonihmig** [comment] 2016-12-14 20:11
Hey @san650, thanks for your (long) answer! ;)

Yes, I did get the fact that a page object component is at first just a POJO, so I also used `create`. (However did not realize you can call `create` directly on the component rather than wrapping it in another object as I did, was a bit stupid...)

I am not so sure if your approach with the separate exports (default as POJO, named wrapped in `create`) is not a bit confusing, at least for novices. I think this may lead to many cases importing the wrong thing and then wondering why it does not work. (Like copy/pasting the page object component import from a page object to an integration test). At least when having to write the imports by yourself (see below for another suggestion).

Your idea having the ability to compose page objects would certainly be the least error prone. I don't know what that means implementation wise though. But would be cool certainly!

Another idea (a separate story basically but still related) I thought about for quite some time is having some blueprint generate all the necessary stuff in one step. It felt always a bit annoying to have to run the blueprints for the component itself and for a matching page object component, and then to have to adapt the generated integration test with the same boilerplate code all the time (basically copy pasting things like the imports of the page object component and the before/afterEach functions, eventually the create stuff, and the integration context calls).  

So how about "overriding" the component blueprint when ember-cli-page-object is used:

```
ember g component foo-bar
``` 

This "overridden" blueprint for component generation would do the following:
* create the component itself with the default blueprint
* create a page object component with the same name (same blueprint as it is now)
* create a slightly modified component-test which includes all the page object boilerplate mentioned above

This does not remove the distinction between a full page object and a POJO component. But it makes the user not having to care about this distinction. As long as they use the blueprints, everything would be setup for him and it just works!

I may try to contribute this feature, if you agree on this being a useful thing!?

**Comment by san650** [comment] 2016-12-14 20:25
I really like this idea. I would like to go in this direction, can we do it for qunit first? We could experiment by doing everything for qunit first, we could support mocha in the future.

Please, start working on this and let us know if you have any question. You can open a WorkInProgress pull request if you want early feedback.

**Comment by simonihmig** [comment] 2016-12-15 08:33
Great. Will try to put something (at least a quick spike) together before xmas if time allows! :)

As a mocha user myself, will try to bring this also to the mocha world asap! ;)

**Comment by simonihmig** [comment] 2016-12-20 12:20
Regarding this feature my idea was to override the default component blueprint when a special flag is set, like `ember g component --page-object` so it creates the component, the (modified) component-test and the page-object-component. Without the flag it should run the default blueprint without any modifications.

I asked about this on the -ember-cli Slack channel, but did not get a real answer. It seems this should be doable, but not without touching private APIs of ember-cli (to lookup the default blueprint und run that if the flag is not present).

The alternative would be to use a different blueprint name like `ember g component-with-page-object` to separate them. But that does not feel so nice I think.

I did not want to really override the default component blueprints without the user having an option to opt in / opt out. If things change there these would have to be kept in sync with the overridden blueprint files in ember-cil-page-object then. Should we worry about this?

What do you think @san650 ?

**Comment by san650** [comment] 2016-12-20 16:51
So current options are:
1. Use `ember g component --page-object` but this is doable only by using ember-cli private API
2. A new blueprint `ember g component-with-page-object` (or another name) and from this blueprint call to `ember g component` blueprint (right?). This doesn't need private API calls
3. Override default blueprint and imitate the original but we would have to keep it in sync.
4. Don't add this feature

So, there's no easy answer:

* Option 1: I would like to investigate a bit more this option and check if it can be done without using private APIs, or evaluate which private APIs have to be used. Do you have a WIP branch with this approach?

* Options 2: we could add a flag to `ember g page-object-component --all foo-bar` that generates the component and test apart from creating the page object (I'm assuming that we can call a blueprint from another blueprint easily).

* Option 3: Seems like a maintenance burden, as you said, we would have to keep it in sync. I would prefer to avoid this option... or evaluate how much maintenance burden will be. We would have to support ember-cli's current tree structure plus the upcoming structure.

* Option 4: Let's investigate a bit the other options first :-). Worst case, we could document a best practice in the website and point people to that document.

@simonihmig if you already have code for option 1, can you push it to a branch? What's your preferred option?

**Comment by simonihmig** [comment] 2016-12-20 17:25
Sorry, no code yet, was just investigating.

Option 1: There is `Blueprint.lookupBlueprint` (https://github.com/ember-cli/ember-cli/blob/master/lib/models/blueprint.js#L1225-L1232) that is public. But I think when choosing the same name as another one (component in this case) this will override it and we are not able to fetch the overridden one with this API. Then there is `Blueprint.lookup` (https://github.com/ember-cli/ember-cli/blob/master/lib/models/blueprint.js#L1245-L1262) which seems to be private, but allows specify the path to look for, which could be used to "unhide" the overridden blueprint by just giving in the path to default blueprints. When deciding for that option, we could try to get this API public or get some other supported way into ember-cli, but probably not in a very short term...

Option 3: yes, not ideal. Currently (and probably in the future as well) the component blueprint is pretty tiny, just a couple of lines, see https://github.com/ember-cli/ember-cli-legacy-blueprints/tree/master/blueprints/component. So the "burden" if we really want to call it like this is not that much. 

I do not like Option 2 very much, feels a bit weird to me ;)

**Comment by simonihmig** [comment] 2016-12-21 15:51
So @san650, what path should we follow? :) I would try Option 3, and maybe switch to Option 1 when there is a way to do so without hitting private APIs. Your opinion?

**Comment by san650** [comment] 2016-12-21 16:02
@simonihmig Agreed, option 3 seems the more viable for now.

**Comment by juanazam** [comment] 2016-12-21 16:24
@simonihmig @san650 I have been following this discussion, I think Option 3 might be an overkill for what we are trying to solve here.

It seems the biggest problem we want to tackle is to provide a simple way to create a component integration test (with all the necessary boilerplate code it needs).

All described options solve that, option 1 would rely on private APIs which is not good and option 3 has a maintenance burden that can be considerable.

Given that the problem is to provide a format for component integration tests using this addon, I think the simplest way is to create a new blueprint that builds exactly that and nothing more.

What do you think?

**Comment by simonihmig** [comment] 2016-12-21 16:35
@juanazam Well, again on the maintenance burden: it is 5 lines of code that have to be "maintained", the 4 lines of the component.js blueprint and the one line containing `{{yield}}` of the template. As you can see here (https://github.com/ember-cli/ember-cli-legacy-blueprints/tree/master/blueprints/component), the last change to that was over a year ago. So, I am fine with taking the part of maintaining that! :)

I think making it easy for user that precedence over making it easy for "us" maintainers, so I am still in favor of Option 3 (possibly Option 1 later)

**Comment by san650** [comment] 2016-12-21 16:39
What do you think about implementing option 3 and discussing on the PR? So, we can discuss over actual code 😃

**Comment by simonihmig** [comment] 2016-12-21 16:48
Makes perfect sense! :)

However unsure if I get to this before xmas, probably in the week after...

**Comment by san650** [comment] 2016-12-21 16:51
No hurries, we really appreciate every contribution and we know most of the people uses his/her spare time to contribute to OSS projects!

**Comment by juanazam** [comment] 2016-12-21 16:53
@simonihmig go ahead, thanks for your contribution in advance and merry Christmas 🎄

**Comment by san650** [comment] 2017-01-20 19:20
This is fixed by the blueprint that generates a component integration test with a page object component.

**Closed by san650** 2017-01-20 19:20 UTC
Labels: feature
