### ISSUE TITLE
Cannot find module 'silent-error'

### ISSUE THREAD

**Issue by datajohnny** [san650/ember-cli-page-object#140] opened 2016-03-01 05:41 UTC
Hi I just, installed the latest version of page-object and when I try to run a generator I got this error:

```Cannot find module 'silent-error'
Error: Cannot find module 'silent-error'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/johnny/Projects/Cometa/FrontEnd/liberty/node_modules/ember-simple-auth/blueprints/authenticator/index.js:2:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)```

I am running ember-cli 2.3.0

Thanks for your assistance

**Comment by san650** [comment] 2016-03-01 21:35
@datajohnny sorry you had troubles with the addon.

Looking at the stack trace you posted, it seems the problem doesn't relate with ember-cli-page-object but it has to do with ember-simple-auth

`node_modules/ember-simple-auth/blueprints/authenticator/index.js:2:19`

It seems to be a problem with `authenticator` blueprint inside `ember-simple-auth` addon.

Can you check if you can reproduce the error uninstalling `ember-simple-auth`?

**Comment by san650** [comment] 2016-03-09 15:55
Hi @datajohnny, I couldn't reproduce the error. Did you tried what I commented above? Do you still have the same issue?

I'm closing the issue for now, if you still can reproduce the error, please reopen it.

**Closed by san650** 2016-03-09 15:55 UTC
Labels: bug, question
