### ISSUE TITLE
Errors running tests since upgrading to v5 of `ember-qunit`

### ISSUE THREAD

**Issue by fran-worley** [san650/ember-cli-page-object#524] opened 2020-12-21 10:47 UTC
Migrating to v5 of ember-qunit causes issues with ember-cli-page-object. I suspect it is to do with the following [breaking change](https://github.com/emberjs/ember-qunit/blob/master/docs/migration.md#remove-ember-test-helpers-modules)

Actual error: 
```
  Error: Could not find module `ember-test-helpers/wait` imported from `ember-cli-page-object/test-support/-private/execution_context/integration`
```

**Comment by cah-briangantzler** [comment] 2020-12-22 23:11
So the problem is a lot bigger than that. The really need to get away from using https://github.com/cibernox/ember-native-dom-helpers as well because that also does an import of ember-test-helpers/wait. We dont want to fix ember-native-dom-helpers either as it really is no longer needed. 

Attempting to remove ember-native-dom-helpers lead to a host of tests breaking that would need rewritten.

In my experiments I also found that fillin will allow you to fill in a disabled element, when removing ember-native-dom-helpers and using fillin from @ember/test-helpers, fillin now fails when the element is disabled, which is the correct thing to do. This prevented me from using my applications tests to test ember-cli-page-object changes because my tests now fail (I have to fix them as well now). There also seems to be a difference in visit, but I did not explore it as the changes just spiraled.

I am hoping one of the maintainers that know a lot more about how this is put together will find the time to fix this.

**Comment by ro0gr** [comment] 2020-12-23 12:16
Thank you guys for raising the issue and investigation!
Removal of old moduleFor integrations is definetily on their way. 
Unfortunately, I'm a bit limited in time currently, but I'll try to find some time this weekend to publish the first beta of v2, which unlocks us to remove the old integrations "properly". Will keep updating the status here in the ticket.

**Comment by cah-briangantzler** [comment] 2020-12-23 15:31
If there are any sub tasks I can help with. Let me know.

**Comment by ro0gr** [comment] 2021-01-06 21:22
I've just published beta.1. A noticeable change is that we've stopped importing adapters(previously known as private ExecutionContexts) eagerly, and now we require to import and set adapters manually in user land, see https://github.com/san650/ember-cli-page-object/pull/511 for some more details. I believe this change should avoid the issue with the ember-native-dom-helpers, which you've mentioned @cah-briangantzler.

> If there are any sub tasks

I'd really like us to add ember-qunit@5 to our test matrix. There was some initial effort already https://github.com/san650/ember-cli-page-object/pull/516, but seems we still need to move it to the finish line, and target it to the v2-beta branch. 
It'd be great, if someone could help with this and make sure ember-qunit@5 is really supported!

**Comment by SergeAstapov** [comment] 2021-01-14 21:11
@ro0gr I opened #529 which is relatively simple fix that could be released as patch version for ember-unit v5 compatibility without need to wait for v2 or upgrade to v2 beta.

**Comment by SergeAstapov** [comment] 2021-01-15 04:56
Created a fix for ember-native-dom-helpers in cibernox/ember-native-dom-helpers#168

**Closed** 2021-01-24 21:21 UTC

**Comment by ro0gr** [comment] 2021-01-24 21:33
ember-qunit@5 support has been released as 1.17.5. Thanks everyone for making it happen! 🚀
